/**
 * 에러 코드 체계
 *
 * 클라이언트에서 에러를 구분하기 위한 코드
 * 메시지는 영어로 유지하고, 클라이언트에서 다국어 처리
 */
export enum ErrorCode {
  // 인증 (AUTH_*)
  AUTH_INVALID_GOOGLE_TOKEN = 'AUTH_INVALID_GOOGLE_TOKEN',
  AUTH_INVALID_APPLE_TOKEN = 'AUTH_INVALID_APPLE_TOKEN',
  AUTH_INVALID_REFRESH_TOKEN = 'AUTH_INVALID_REFRESH_TOKEN',
  AUTH_EMAIL_REQUIRED = 'AUTH_EMAIL_REQUIRED',
  AUTH_EMAIL_ALREADY_EXISTS = 'AUTH_EMAIL_ALREADY_EXISTS',
  AUTH_DEV_ONLY = 'AUTH_DEV_ONLY',

  // 사용자 (USER_*)
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_INVALID_TIMEZONE = 'USER_INVALID_TIMEZONE',
  USER_NO_FCM_TOKEN = 'USER_NO_FCM_TOKEN',

  // 기념일 (OCCASION_*)
  OCCASION_NOT_FOUND = 'OCCASION_NOT_FOUND',
  OCCASION_FORBIDDEN = 'OCCASION_FORBIDDEN',
  OCCASION_PIN_LIMIT_EXCEEDED = 'OCCASION_PIN_LIMIT_EXCEEDED',
  OCCASION_MILESTONE_LIMIT_EXCEEDED = 'OCCASION_MILESTONE_LIMIT_EXCEEDED',

  // 마일스톤 (MILESTONE_*)
  MILESTONE_NOT_FOUND = 'MILESTONE_NOT_FOUND',

  // 서버 오류
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}
